### ISSUE TITLE
Potential test framework bugs

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#3004]
While doing large quantities of test runs for #3003, both @chromatic and I saw framework failures. 

- [chromatic's logs](https://gist.github.com/chromatic/dfe51f606f0b0f89c393fa9c63aaa4ab)
- [my logs](https://gist.github.com/patricklodder/38f3cc2909a643f4a334792768248c25)

Could benefit from analysis

**Comment by victorsk2019** [comment]
There could also be issues with 1.21 tests:

```
Temporary test directory at /tmp/test_runner_Đ_🏃_20220621_101402
Running Unit Tests for Test Framework Modules
..........
----------------------------------------------------------------------
Ran 10 tests in 0.911s

OK
2022-06-21T17:14:03.056000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_Đ_🏃_20220621_101402/cache
Proxy: http://__cookie__:0af5fcad823b8d292cdaba60c294320728ebe6af8fb48e31212c79e2021bc170@127.0.0.1:20661
Proxy: http://__cookie__:0af5fcad823b8d292cdaba60c294320728ebe6af8fb48e31212c79e2021bc170@127.0.0.1:20661
Proxy: http://__cookie__:0af5fcad823b8d292cdaba60c294320728ebe6af8fb48e31212c79e2021bc170@127.0.0.1:20661
2022-06-21T17:14:03.568000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/home/dogecoin/projects/fromgit/dogecoin-1.21-dev/test/functional/test_framework/test_framework.py", line 127, in main
    self.setup()
  File "/home/dogecoin/projects/fromgit/dogecoin-1.21-dev/test/functional/test_framework/test_framework.py", line 263, in setup
    self.setup_chain()
  File "/home/dogecoin/projects/fromgit/dogecoin-1.21-dev/test/functional/test_framework/test_framework.py", line 354, in setup_chain
    self._initialize_chain()
  File "/home/dogecoin/projects/fromgit/dogecoin-1.21-dev/test/functional/test_framework/test_framework.py", line 730, in _initialize_chain
    cache_node.generatetoaddress(
  File "/home/dogecoin/projects/fromgit/dogecoin-1.21-dev/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/home/dogecoin/projects/fromgit/dogecoin-1.21-dev/test/functional/test_framework/authproxy.py", line 146, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: CreateNewBlock: TestBlockValidity failed: bad-witness-nonce-size, ContextualCheckBlock : invalid witness reserved value size (-1)
2022-06-21T17:14:03.619000Z TestFramework (INFO): Stopping nodes
2022-06-21T17:14:04.123000Z TestFramework (WARNING): Not cleaning up dir /tmp/test_runner_Đ_🏃_20220621_101402/cache
2022-06-21T17:14:04.123000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/test_runner_Đ_🏃_20220621_101402/cache/test_framework.log
2022-06-21T17:14:04.124000Z TestFramework (ERROR): 
2022-06-21T17:14:04.124000Z TestFramework (ERROR): Hint: Call /home/dogecoin/projects/fromgit/dogecoin-1.21-dev/test/functional/combine_logs.py '/tmp/test_runner_Đ_🏃_20220621_101402/cache' to consolidate all logs
2022-06-21T17:14:04.124000Z TestFramework (ERROR): 
2022-06-21T17:14:04.125000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2022-06-21T17:14:04.125000Z TestFramework (ERROR): https://github.com/dogecoin/dogecoin/issues
2022-06-21T17:14:04.125000Z TestFramework (ERROR): 
Traceback (most recent call last):
  File "/home/dogecoin/projects/fromgit/dogecoin-1.21-dev/test/functional/test_runner.py", line 801, in <module>
    main()
  File "/home/dogecoin/projects/fromgit/dogecoin-1.21-dev/test/functional/test_runner.py", line 442, in main
    run_tests(
  File "/home/dogecoin/projects/fromgit/dogecoin-1.21-dev/test/functional/test_runner.py", line 496, in run_tests
    subprocess.check_output([sys.executable, tests_dir + 'create_cache.py'] + flags + ["--tmpdir=%s/cache" % tmpdir])
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/lib/python-exec/python3.9/python3', '/home/dogecoin/projects/fromgit/dogecoin-1.21-dev/test/functional/create_cache.py', '--cachedir=/home/dogecoin/projects/fromgit/dogecoin-1.21-dev/test/cache', '--configfile=/home/dogecoin/projects/fromgit/dogecoin-1.21-dev/test/functional/../config.ini', '--tmpdir=/tmp/test_runner_Đ_🏃_20220621_101402/cache']' returned non-zero exit status 1.
```
But here I think the problem is with SegWit test part.
