### ISSUE TITLE
[bug] The CI process errors on installing `ltc_scrypt`

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/dogecoin#3583]
# Bug Report

The CI process errors on installing `ltc_scrypt`. #3582 works around this issue by pinning version 70.3.0 to retain a working CI. However, this is not a good long-term solution because with that, we cannot upgrade `setuptools` in case of a critical bug. Maybe we can do something in [dogecoin/ltc-scrypt](https://github.com/dogecoin/ltc-scrypt) to modernize the tooling, but the issue remains that the CI behaves differently than Docker Library, which is something to look out for; it would be good to pin versions regardless of the solution but it's no good if we're stuck on a specific pinned version and cannot change that.

**Current behavior:**

On any CI job that runs the rpc tests:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22946    0 22946    0     0   107k      0 --:--:-- --:--:-- --:--:--  107k
v1.0.1.tar.gz: OK
Processing ./v1.0.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-5rr4j52q/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-5rr4j52q/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-5rr4j52q/pip-egg-info
         cwd: /tmp/pip-req-build-5rr4j52q/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/runner/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 19, in <module>
        from .dist import Distribution
      File "/home/runner/.local/lib/python3.8/site-packages/setuptools/dist.py", line 30, in <module>
        from . import _entry_points
      File "/home/runner/.local/lib/python3.8/site-packages/setuptools/_entry_points.py", line 44, in <module>
        def validate(eps: metadata.EntryPoints):
    AttributeError: module 'importlib_metadata' has no attribute 'EntryPoints'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
``` 

**Expected behavior**

The CI image works just as the Docker Library image works:

```
RUN python3 -m pip install setuptools==71.0.3 --upgrade
Collecting setuptools==71.0.3
  Downloading setuptools-71.0.3-py3-none-any.whl (2.3 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 45.2.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'setuptools'. No files were found to uninstall.
Successfully installed setuptools-71.0.3

RUN curl -L -O https://github.com/dogecoin/ltc-scrypt/archive/refs/tags/v1.0.1.tar.gz  && python3 -m pip install v1.0.1.tar.gz --user
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22946    0 22946    0     0  52388      0 --:--:-- --:--:-- --:--:-- 52388
Processing ./v1.0.1.tar.gz
Building wheels for collected packages: ltc-scrypt
  Building wheel for ltc-scrypt (setup.py): started
  Building wheel for ltc-scrypt (setup.py): finished with status 'done'
  Created wheel for ltc-scrypt: filename=ltc_scrypt-1.0.1-cp38-cp38-linux_x86_64.whl size=43354 sha256=37dffc0368965bb60eb8220116c81f36e0d074a448c781f0cc7ee33d8a6debb4
  Stored in directory: /tmp/pip-ephem-wheel-cache-j1f81kse/wheels/53/1a/a1/95759412a7392ad976630e8502efe7af5353e4e3c1a16490c5
Successfully built ltc-scrypt
Installing collected packages: ltc-scrypt
Successfully installed ltc-scrypt-1.0.1
```

**Dockerfile to reproduce the success case:**

```Dockerfile
FROM ubuntu:focal

RUN apt update \
 && apt install -y python3 python3-pip python3-setuptools curl

ARG ST_VERSION=71.0.3
RUN python3 -m pip install setuptools==${ST_VERSION} --upgrade

WORKDIR /tmp/build

ARG TAG=v1.0.1
RUN curl -L -O https://github.com/dogecoin/ltc-scrypt/archive/refs/tags/${TAG}.tar.gz \
 && python3 -m pip install ${TAG}.tar.gz --user
```

**More information:**

The versions installed look to be the same for both images:

- `python3` `3.8.2-0ubuntu2`
- `python3-wheel` `0.34.2-1ubuntu0.1`
- `python3-pip` `20.0.2-5ubuntu1.10`

**Comment by oxqnd** [comment]
Hi, can I try fixing this issue?

**Comment by oxqnd** [comment]
Alright, I’ll take a look and see what I can do.

**Comment by oxqnd** [comment]
Hi @patricklodder , just following up — I’ve submitted the fix as [PR #13](https://github.com/dogecoin/ltc-scrypt/pull/13) on the `ltc-scrypt` repository.

The changes are fully tested and should resolve the setuptools>=68 build issue. Let me know if anything else is needed before tagging a release.

Thanks again!
